import { Badge, LearningPath, Question, RankingEntry } from './types';
export { LESSONS, TOPICS } from './generated/content-manifest';

export const QUESTIONS: Question[] = [
  {
    id: 'q-natural-1',
    lessonId: 'natural-numbers-reading',
    text: 'Qual número é maior?',
    options: ['12.305', '12.350', '12.053', '12.035'],
    correctAnswer: 1,
    explanation: 'Comparando as ordens, 12.350 é maior que 12.305.',
    hint: 'Compare os algarismos da esquerda para a direita.',
  },
  {
    id: 'q-fractions-1',
    lessonId: 'fractions-intro',
    text: 'Se uma barra tem 12 partes e você come 6, qual fração representa a parte comida em forma simplificada?',
    options: ['6/12', '1/2', '3/4', '2/3'],
    correctAnswer: 1,
    explanation: '6/12 simplifica para 1/2 porque numerador e denominador podem ser divididos por 6.',
    hint: 'Simplifique a fração dividindo numerador e denominador pelo mesmo número.',
  },
  {
    id: 'q-fractions-2',
    lessonId: 'fractions-operations',
    text: 'Quanto vale 1/2 + 1/4?',
    options: ['2/6', '3/4', '1/6', '2/4'],
    correctAnswer: 1,
    explanation: 'Transforme 1/2 em 2/4. Depois some: 2/4 + 1/4 = 3/4.',
    hint: 'Use denominador comum 4.',
  },
  {
    id: 'q-ratio-1',
    lessonId: 'ratio-concept',
    text: 'Se um mapa usa escala 1:100, 2 cm no mapa representam quantos cm reais?',
    options: ['20', '200', '2.000', '10'],
    correctAnswer: 1,
    explanation: 'A escala 1:100 indica que 1 cm no mapa corresponde a 100 cm reais. Então 2 cm correspondem a 200 cm.',
    hint: 'Multiplique a medida do mapa pelo fator da escala.',
  },
  {
    id: 'q-linear-1',
    lessonId: 'linear-intro',
    text: 'Resolva a equação x + 9 = 14.',
    options: ['x = 23', 'x = 5', 'x = 14', 'x = 9'],
    correctAnswer: 1,
    explanation: 'Subtraia 9 dos dois lados da equação: x = 14 - 9 = 5.',
    hint: 'Para isolar x, leve o 9 para o outro lado subtraindo.',
  },
  {
    id: 'q-linear-2',
    lessonId: 'linear-problems',
    text: 'O triplo de um número menos 2 é 16. Qual é esse número?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 2,
    explanation: 'Monte 3x - 2 = 16. Então 3x = 18 e x = 6.',
    hint: 'Transforme a frase em 3x - 2 = 16.',
  },
  {
    id: 'q-geometry-1',
    lessonId: 'geometry-triangles',
    text: 'Qual é a área de um triângulo com base 8 e altura 6?',
    options: ['48', '24', '14', '28'],
    correctAnswer: 1,
    explanation: 'A área é (8 × 6) / 2 = 48 / 2 = 24.',
    hint: 'Use a fórmula base vezes altura dividido por 2.',
  },
  {
    id: 'q-geometry-2',
    lessonId: 'geometry-perimeter',
    text: 'Um retângulo tem lados 5 e 3. Qual é o perímetro?',
    options: ['8', '15', '16', '30'],
    correctAnswer: 2,
    explanation: 'Perímetro é a soma de todos os lados: 5 + 3 + 5 + 3 = 16.',
    hint: 'Some todos os lados da figura.',
  },
  {
    id: 'q-functions-1',
    lessonId: 'functions-intro',
    text: 'Se f(x) = 2x + 1, qual é o valor de f(4)?',
    options: ['9', '8', '7', '5'],
    correctAnswer: 0,
    explanation: 'f(4) = 2 × 4 + 1 = 9.',
    hint: 'Substitua x por 4 na expressão.',
  },
  {
    id: 'q-functions-2',
    lessonId: 'functions-graphs',
    text: 'Se o gráfico de uma reta sobe da esquerda para a direita, a função é:',
    options: ['Constante', 'Decrescente', 'Crescente', 'Indefinida'],
    correctAnswer: 2,
    explanation: 'Quando a reta sobe da esquerda para a direita, a função é crescente.',
    hint: 'Observe o comportamento da reta ao avançar no eixo x.',
  },
  {
    id: 'q-affine-1',
    lessonId: 'affine-concept',
    text: 'Na função y = 3x + 2, qual é o coeficiente angular?',
    options: ['2', '3', '5', '0'],
    correctAnswer: 1,
    explanation: 'Na forma y = ax + b, o coeficiente angular é o número que multiplica x, neste caso 3.',
    hint: 'Olhe para o número que acompanha x.',
  },
  {
    id: 'q-trig-1',
    lessonId: 'trigonometry-intro',
    text: 'Se o cateto oposto mede 3 e a hipotenusa mede 5, qual é o seno do ângulo?',
    options: ['3/5', '5/3', '3/2', '2/5'],
    correctAnswer: 0,
    explanation: 'Seno = cateto oposto / hipotenusa = 3/5.',
    hint: 'Seno sempre usa cateto oposto dividido pela hipotenusa.',
  },
  {
    id: 'q-trig-2',
    lessonId: 'trigonometry-angles',
    text: 'Qual é o valor de sen 30°?',
    options: ['1', '1/2', '√2/2', '√3/2'],
    correctAnswer: 1,
    explanation: 'O valor notável de sen 30° é 1/2.',
    hint: 'É um dos valores clássicos mais cobrados.',
  },
];

export const BADGES: Badge[] = [
  {
    id: 'fraction-master',
    title: 'Mestre das Frações',
    description: 'Fez 100% em todas as lições de Frações.',
    icon: 'Divide',
    requirement: 'fractions',
  },
  {
    id: 'algebra-warrior',
    title: 'Guerreiro da Álgebra',
    description: 'Dominou completamente Equações do 1º Grau.',
    icon: 'Variable',
    requirement: 'linear-equations',
  },
  {
    id: 'geometry-explorer',
    title: 'Explorador Geométrico',
    description: 'Concluiu Geometria Básica com acerto perfeito.',
    icon: 'Square',
    requirement: 'geometry-basics',
  },
  {
    id: 'graph-reader',
    title: 'Leitor de Gráficos',
    description: 'Fechou o módulo de Funções sem erros.',
    icon: 'Activity',
    requirement: 'functions',
  },
  {
    id: 'trig-scout',
    title: 'Batedor Trigonométrico',
    description: 'Acertou todas as lições de Trigonometria.',
    icon: 'Triangle',
    requirement: 'trigonometry',
  },
  {
    id: 'finance-operator',
    title: 'Operador Financeiro',
    description: 'Concluiu Matemática Financeira com 100%.',
    icon: 'Wallet',
    requirement: 'math-finance',
  },
];

export const PATHS: LearningPath[] = [
  {
    id: 'exam-prep',
    title: 'Recuperação para Provas',
    description: 'Reforça a base de números, equações e leitura de gráficos.',
    topicIds: ['fractions', 'linear-equations', 'functions'],
    color: '#FF6B6B',
    estimatedWeeks: 4,
    focus: 'Base, recomposição de conteúdo e ganho rápido de confiança.',
    featuredLessonId: 'fractions-intro',
  },
  {
    id: 'geometry-deep',
    title: 'Aprofundamento em Geometria',
    description: 'Parte do plano, passa por semelhança e fecha com trigonometria.',
    topicIds: ['geometry-basics', 'geometry-similarity', 'trigonometry', 'analytic-geometry'],
    color: '#4ECDC4',
    estimatedWeeks: 6,
    focus: 'Visualização espacial, triângulos e leitura geométrica para provas.',
    featuredLessonId: 'geometry-perimeter',
  },
  {
    id: 'algebra-track',
    title: 'Trilha de Álgebra',
    description: 'Cobre linguagem algébrica, equações e funções da base ao Médio.',
    topicIds: ['algebra-foundations', 'linear-equations', 'functions', 'function-affine', 'function-quadratic'],
    color: '#FFE66D',
    estimatedWeeks: 7,
    focus: 'Progressão natural para vestibular e resolução simbólica.',
    featuredLessonId: 'linear-intro',
  },
  {
    id: 'vestibular-essentials',
    title: 'Essenciais para Vestibular',
    description: 'Seleciona os blocos mais recorrentes nas provas.',
    topicIds: ['function-affine', 'function-quadratic', 'trigonometry', 'combinatorics-probability', 'descriptive-statistics', 'math-finance'],
    color: '#B8F2E6',
    estimatedWeeks: 8,
    focus: 'Funções, análise de dados, trigonometria e interpretação de problemas.',
    featuredLessonId: 'affine-concept',
  },
];

export const MOCK_RANKING: RankingEntry[] = [
  { name: 'Ana Silva', points: 2450, avatar: 'https://picsum.photos/seed/ana/100' },
  { name: 'Bruno Costa', points: 2100, avatar: 'https://picsum.photos/seed/bruno/100' },
  { name: 'Camila Rocha', points: 1820, avatar: 'https://picsum.photos/seed/camila/100' },
  { name: 'Diego Nunes', points: 1690, avatar: 'https://picsum.photos/seed/diego/100' },
  { name: 'Erika Souza', points: 1580, avatar: 'https://picsum.photos/seed/erika/100' },
];
